default: &default
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:secret@localhost:5432") %>

development:
  <<: *default

test:
  adapter: test

production:
  <<: *default
  channel_prefix: efficio_production
