default: &default
  silence_polling: true
  dispatchers:
    - polling_interval: 5
      batch_size: 500
  workers:
    - queues: "*"
      threads: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
      processes: 1
      polling_interval: 1

development:
  <<: *default
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 1

test:
  <<: *default

production:
silence_polling <<: *default
